### ISSUE TITLE
Update GitVersion configuration

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#225]
## Todo

- [x] Review yaml file
- [x] Edit for release *alpha* when branch is `release/xx.xx.xx`
- [x] Edit for release *beta* when branch is `develop`
- [x] Edit for release final when branch us `master`
- [x] Incremenation does not work. When should be `beta.2` it's `beta.1`

## Inspiration
https://github.com/GitTools/GitVersion/blob/af40918ea1ccda27b3f779be67a63cec9426f909/GitVersion.yml#L1

## Documentation

* [Documentation (Continuous Delivery)](https://gitversion.net/docs/reference/modes/continuous-delivery)
* [Requirements](https://gitversion.net/docs/reference/requirements)
* []Configuration(https://gitversion.net/docs/reference/configuration)

**Comment by jibedoubleve** [comment]
# Documentation
## Explanation on *Continuous Delivery*

* [Documentation](https://gitversion.net/docs/reference/modes/continuous-delivery)
