### ISSUE TITLE
Update for web plugin

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#293]
This is all the tasks that have to be done to finalise the web plugins. This is the analysis phase, every tasks should be moved into its one ticket.

# Tasks

- [x] Check version and refuse install when version is less than the installed one. (#310)
- [x] Check which plugins are installed and don't display them if already installed (#300)
- [x] Show installed plugin when version id newer (show this is a version update) (#311)
