### ISSUE TITLE
Add alias alternative with other parameters

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#314]
# Explanations

You set up, for instance, an alias for Visual Studio Code (`code`) but you want to have an alias to open `project1.sln`
 and another to open `project2.sln`. Now, to do it, you duplicate the alias and specialise it with your parameters. 

It could be simpler to create alias `code` and directly configure the different subaliases. So you configure it once and when you make a search on `code`, you have a result like this:

```
- code
-- project1.sln
-- project2.sln
```

# Notes about implementation

- Look at the `repositories` because I see we can use them for this feature
- The ui should simply have a `DataGridView` for the alternative parameters
- Alternative parameters should be concatenated to the parameters setup to the alias
- Probably the DB will need a table `alias_parameter` link to the table `alias`

# Tasks
## Create and Update
- [x] Add table `alias_parameters`
```sql
create table alias_parameters (
   id integer primary key,
   id_alias integer,
   parameters text,
   foreign key(id_alias) references alias(id)
);
```
- [x] In the `ViewModel`, add a list of parameters
- [x] When saving, update `alias_parameters`
- [x] ~~When alias has parameters, set `hidden` to `true`~~ **OR**
- [x] Update search query to select only alias without parameters
## Delete
- [x] Delete all the parameters linked to the alias on deletion
- [x] ~~If all the parameters are deleted, set `hidden` to `false`~~
## Search
- [x] Create a reporisoty
- [x] select all the alias with parameters
