### ISSUE TITLE
Create an icon when the alias is only an URL

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#334]
# ToDo

- [ ] Check whether alias is a directory; if **yes**, add directory icon
- [ ] Check whether alias is an URL; if **yes**, add hyperlink icon
- [ ] Add tool to update icons for all aliases
