### ISSUE TITLE
Thumbnail managemenet can be optimised

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#399]
I can early return when thumbnails is already configured and saved in the image reposiotry

[Documentation](https://github.com/jibedoubleve/lanceur-bis/wiki/DEV_thumbnails)

# Todo

- [x] Early quit when thumbnail exists
- [x] Download favicon if not exists
- [x] Retrieve thumbnail for Packaged Applications
