### ISSUE TITLE
Add confirmation on alias with side effects

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#491]
# Description

The alias needs to incorporate an `IsExecutionConfirmationRequired` property. When set to `true`, it should prompt a confirmation MessageBox, allowing users the option to cancel if needed.

# Tasks
 - [x] Update SQL (create alias, `SQLiteRepository`)
 - [x] Update SQL  (update alias, `SQLiteRepository`)
 - [x] Update Model (`QueryResult`)
 - [x] Update Execution to handle `IsExecutionConfirmationRequired`
 - [x] Update UI to allow user set `IsExecutionConfirmationRequired`
 - [x] Unit Tests or System Tests

# Analysis
As shown below, `AliasQueryResult` is a good candidate to add a property `public bool IsExecutionConfirmationRequired { get; set; }`.

Next, add a test in the `MainViewModel.OnExecuteAliasAsync(...)` method to check whether the confirmation is mandatory.

![image](https://github.com/jibedoubleve/lanceur-bis/assets/2678545/7d34d171-06dc-470c-aa4b-d5d83f1628f4)

Use dotnet tool [PlantUmlClassDiagramGenerator](https://khalidabuhakmeh.com/dotnet-class-diagrams-in-jetbrains-rider-with-plantuml) to display class diagrams
