### ISSUE TITLE
Add New Store to Enable Search in Firefox and Chrome Bookmark

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#500]
# Tasks
- [x] Create boomark management for Chrome
- [x] Create bookmark management for Firefox
- [x] Add settings to select Chrome or Firefox

# Information
## Bookmarks in Chrome 
* The bookmarks are saved in `$env:APPDATA\..\Local\Google\Chrome\User Data\Default\Bookmarks`
* `jq '.. | objects | select(has("name") and has("url")) | {name, url}' "$env:APPDATA\..\Local\Google\Chrome\User Data\Default\Bookmarks"
` gives a flat list of bookmarks

## Bookmarks in Firefox
Here's the sql to select all the bookmarks
```sql
select 
	b.title,
	p.url
from 
	moz_bookmarks b
	inner join moz_places p on b.fk = p.id
where type = 1;
```

The profile can be found in the ini file
* `%AppData%\Mozilla\Firefox\profiles.ini` for **Firefox**
* `%AppData%\zen\profiles.ini` for **Zen Browser**

The default profile has this line: `Default=1`
