### ISSUE TITLE
Create a repository for plugins

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#51]
Create a repository where user can find & download plugins

# Todo
- [ ] Create a GitHub project where you can download the plugins
- [ ] Download any plugins from the application
- [ ] Automatise the release in the GitHub page
