### ISSUE TITLE
Remove session feature

### ISSUE THREAD

**Issue by probel-software** [jibedoubleve/lanceur-bis#513]
The session management feature is unused and complicates the application.

We should remove it.

# Tasks
 - [x] **Database**
     - [x] delete from `alias_usage`
     - [x] delete from `alias`
     - [x] drop table `alias_session`
     - [x] `drop view if exists stat_usage_per_app_v;`
     - [x] `drop view if exists stat_usage_per_day_v;`
     - [x] `drop view if exists stat_usage_per_month_v;`
     - [x] `drop view if exists stat_usage_per_day_of_week_v;`
     - [x] `drop view if exists stat_usage_per_hour_in_day_v;`
     - [x] `drop view if exists data_not_used_v;`
     - [x] `drop view if exists stat_execution_count_v;`
     - [x] `drop view if exists stat_history_v;`
     - [x] `drop view if exists data_doubloons_v;`
 - [x] **User Interface**
     - [x] Session View
     - [x] Settings: default session
     - [x] Keyword session
     - [x] Remove session name from main view
 - [x] **Backend**

## Database

![Image](https://github.com/user-attachments/assets/8d60a142-0198-4b43-8a28-0e571eb668af)
