### ISSUE TITLE
Cannot add packaged app

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#6]
# Todo
 - [x] Fix issue
 - [x] Make new methods async
 - [x] Add icon to alias
 - [x] ~~Move validation out of `private async Task<Unit> OnSaveOrUpdateAlias(AliasQueryResult alias)`. The idea is to create an `UpdateAction`~~
 - [x] Optimise UI (show when working)
 - [x] Check whether fix is working when updating an existing keyword
