### ISSUE TITLE
Rename tag

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#85]
# Description

![image](https://user-images.githubusercontent.com/2678545/212467403-ba712a13-a130-49c9-85d3-bf78ff38d5ef.png)

- [ ] Rename tag from `to be reviewed` to `to be investigated`
- [ ] Create taf `Analysis`

# Todo

- [ ] Rename tag in GitHub
- [ ] Update GitRelease yaml file
